### ISSUE TITLE
Check password before submit

### ISSUE THREAD

**Issue by felipedreis** [sauloantuness/maratona#1]
When the user submits a problem with wrong user password, the script doesn't check the password and gives an error. 
You can see the stacktrace above:  

```
Type your password: 
Submited!
Traceback (most recent call last):
  File "uri.py", line 134, in <module>
    uri.getStatus()
  File "uri.py", line 111, in getStatus
    print answer[1].split('>')[-1]
IndexError: list index out of range
```

**Comment by sauloantuness** [comment]
Thanks for the comment. This issue has been solved in the last commit.
